// data.js — 자동 생성됨 (빌드시 Airtable 데이터로 교체)
// 로컬 테스트용 초기 데이터 = 시연용 가짜 공고 14건 + 기관 19곳

var institutions = {
  snu: { name: '서울대학교 언어교육원', type: '대학 어학당', country: '한국', city: '서울 관악구', website: 'lei.snu.ac.kr', desc: '서울대학교 부설 한국어 교육기관. 외국인 유학생 대상 정규/단기 한국어 과정을 운영합니다.' },
  yonsei: { name: '연세대학교 한국어학당', type: '대학 어학당', country: '한국', city: '서울 서대문구', website: 'ko.yonsei.ac.kr', desc: '국내 최대 규모의 한국어 교육기관 중 하나. 정규 과정과 다양한 특별 과정을 운영합니다.' },
  ewha: { name: '이화여자대학교 언어교육원', type: '대학 어학당', country: '한국', city: '서울 서대문구', website: 'elc.ewha.ac.kr', desc: '이화여자대학교 부설 어학원으로 한국어 교육 과정을 운영합니다.' },
  sejong: { name: '세종학당재단', type: '세종학당', country: '한국', city: '서울 종로구', website: 'ksif.or.kr', desc: '전 세계 84개국 244개소의 세종학당을 운영하는 한국어 보급 공공기관.' },
  ucla: { name: 'UCLA Asian Languages & Cultures', type: '대학·대학원', country: '미국', city: 'Los Angeles, CA', website: 'alc.ucla.edu', desc: 'UCLA의 아시아 언어·문화학과. 한국학 전공 학생 대상 한국어 강의 운영.' },
  toronto: { name: 'University of Toronto, East Asian Studies', type: '대학·대학원', country: '캐나다', city: 'Toronto, ON', website: 'eas.utoronto.ca', desc: '캐나다 최대 한국학 프로그램 중 하나를 운영하는 동아시아학과.' },
  waseda: { name: '와세다대학 한국어교육연구센터', type: '대학·대학원', country: '일본', city: '도쿄', website: 'waseda.jp', desc: '와세다대학에서 한국어 교육과 한국학 연구를 진행하는 센터.' },
  sydney: { name: 'University of Sydney, Korean Studies', type: '대학·대학원', country: '호주', city: 'Sydney, NSW', website: 'sydney.edu.au', desc: '호주 시드니대학교 아시아학과 내 한국학 프로그램.' },
  hochiminh: { name: '호치민 인문사회과학대학 한국학과', type: '대학·대학원', country: '베트남', city: '호치민', website: 'hcmussh.edu.vn', desc: '베트남 호치민 지역의 대표적인 한국학 학과.' },
  gangnam: { name: '강남 토픽 한국어학원', type: '사설 어학원', country: '한국', city: '서울 강남구', website: 'gangnamtopik.kr', desc: 'TOPIK 시험 대비 및 비즈니스 한국어 전문 어학원.' },
  italki: { name: 'Lingoo Korean (온라인 플랫폼)', type: '온라인 플랫폼', country: '온라인', city: '온라인', website: 'lingookorean.com', desc: '전 세계 학습자와 한국어 튜터를 연결하는 1:1 화상 수업 플랫폼.' },
  preply: { name: 'KoreanGo (온라인 플랫폼)', type: '온라인 플랫폼', country: '온라인', city: '온라인', website: 'koreango.com', desc: '한국어 학습 전문 1:1 온라인 튜터링 플랫폼.' },
  samsung: { name: '삼성전자 글로벌인재개발팀', type: '기업 출강', country: '한국', city: '경기 수원', website: 'samsung.com', desc: '삼성전자 임직원 및 해외 주재원·외국인 직원 대상 한국어 교육 운영.' },
  goyang: { name: '고양초등학교', type: '초등학교', country: '한국', city: '경기 고양시 덕양구', website: 'goyang.es.kr', desc: '경기도 고양시 소재 초등학교. 중도입국자녀·다문화학생 대상 한국어교실을 운영합니다.' },
  caritas: { name: '인천 까리따스 이주민문화센터', type: '다문화·가족센터', country: '한국', city: '인천', website: 'caritas-ic.or.kr', desc: '인천 지역 이주민·결혼이민자 대상 사회통합프로그램과 한국어 교육을 운영하는 다문화센터.' },
  darakwon: { name: '다락원 한국어교재', type: '출판사', country: '한국', city: '서울 마포', website: 'darakwon.co.kr', desc: '한국어 교재 출판 전문 출판사. 외국인 학습자용 다양한 한국어 교재 발간.' },
  ebs: { name: 'EBS 한국어 콘텐츠팀', type: '방송사', country: '한국', city: '경기 고양', website: 'ebs.co.kr', desc: 'EBS 한국어 학습 콘텐츠(방송·온라인) 기획·제작 부서.' },
  nikl: { name: '국립국어원', type: '연구기관', country: '한국', city: '서울 강서', website: 'korean.go.kr', desc: '국립국어원 한국어교육 정책 연구 및 TOPIK·교재 평가.' },
  kccuk: { name: '주영국 한국문화원', type: '공공기관', country: '영국', city: 'London', website: 'kccuk.org.uk', desc: '주영국 한국문화원 한국어 강좌 운영 및 교육 프로그램 기획.' },
  kef: { name: '한국어교육진흥재단', type: '연구기관', country: '한국', city: '서울', website: 'kef.or.kr', desc: '한국어교육 정책 연구·사업 기획 재단법인.' },
};

var jobs = [
  {
    id: 1, inst: 'snu',
    title: '한국어 정규과정 시간강사 모집 (2026 가을학기)',
    country: '한국', region: '서울', type: '대학 어학당', employment: '시간강사', category: '강사', mode: '대면',
    salary: '시급 60,000원 (수업 기준)', salaryDisclosed: true,
    cert: '필수', degree: '석사', experience: '경력필수', visa: false,
    deadline: 8, posted: '3일 전', verified: true,
    desc: '서울대학교 언어교육원 한국어 정규과정에서 외국인 학습자를 대상으로 한국어를 강의할 시간강사를 모집합니다.',
    quals: '- 한국어교원자격증 2급 이상 소지자\n- 한국어교육학(또는 외국어로서의 한국어교육) 석사 학위 소지자\n- 외국인 대상 한국어 강의 경력 2년 이상',
    preferred: '박사 학위 소지자, 영어 가능자, 3급 이상 자격증 소지자',
    apply: '본 기관 홈페이지 채용공고 게시판에서 지원서·자기소개서·이력서를 이메일로 접수',
    badges: ['salary','urgent','verified']
  },
  {
    id: 2, inst: 'yonsei',
    title: '한국어학당 비전임 강사 채용 (영주권자 포함)',
    country: '한국', region: '서울', type: '대학 어학당', employment: '초빙·비전임', category: '강사', mode: '대면',
    salary: '월 350~400만원 (경력 협의)', salaryDisclosed: true,
    cert: '필수', degree: '석사', experience: '경력필수', visa: false,
    deadline: 21, posted: '5일 전', verified: true,
    desc: '연세대학교 한국어학당 정규과정 및 특별과정 강의를 담당할 비전임 강사를 모집합니다.',
    quals: '- 한국어교육 관련 석사 이상\n- 한국어교원자격증 2급 이상\n- 외국인 대상 한국어 강의 경력 3년 이상',
    preferred: '영어·중국어·일본어 등 외국어 가능자',
    apply: '한국어학당 홈페이지 양식 다운로드 후 이메일 제출',
    badges: ['salary','verified']
  },
  {
    id: 3, inst: 'ewha',
    title: '이화여대 한국어 단기과정 강사 (여름학기)',
    country: '한국', region: '서울', type: '대학 어학당', employment: '시간강사', category: '강사', mode: '하이브리드',
    salary: '협의', salaryDisclosed: false,
    cert: '우대', degree: '석사', experience: '신입가능', visa: false,
    deadline: 4, posted: '1일 전', verified: true,
    desc: '여름 단기 한국어 집중과정 강의를 담당할 시간강사를 모집합니다. 일부 수업은 온라인 병행 운영.',
    quals: '- 한국어교육 관련 석사 과정 이수 중 또는 수료\n- 외국인 대상 한국어 수업 경험',
    preferred: '한국어교원자격증 보유자',
    apply: '언어교육원 채용 페이지에서 지원',
    badges: ['urgent','junior','verified']
  },
  {
    id: 4, inst: 'sejong',
    title: '2026년 해외 세종학당 파견 한국어교원 모집',
    country: '한국', region: '해외 파견', type: '세종학당', employment: '센터 강사', category: '강사', mode: '대면',
    salary: '월 250~350만원 + 항공·체재비 지원', salaryDisclosed: true,
    cert: '필수', degree: '학사', experience: '경력필수', visa: true,
    deadline: 35, posted: '오늘', verified: true,
    desc: '전 세계 세종학당에 파견되어 한국어 및 한국문화 강의를 담당할 한국어교원을 모집합니다. (총 60명)',
    quals: '- 대한민국 국적자\n- 한국어교원자격증 2급 이상\n- 외국인 대상 한국어 강의 경력 1년 이상',
    preferred: '파견 국가 언어 가능자, 해외 거주·체류 경험자',
    apply: '세종학당재단 채용 시스템(ksif.or.kr) 온라인 지원',
    badges: ['salary','visa','verified']
  },
  {
    id: 5, inst: 'ucla',
    title: 'Korean Language Lecturer (Full-time)',
    country: '미국', region: 'Los Angeles, CA', type: '대학·대학원', employment: '초빙·비전임', category: '강사', mode: '대면',
    salary: 'USD 65,000~78,000 / year', salaryDisclosed: true,
    cert: '우대', degree: '박사', experience: '경력필수', visa: true,
    deadline: 28, posted: '2일 전', verified: true,
    desc: 'UCLA Asian Languages & Cultures 학부에서 학부생 대상 한국어 강의(초급~고급)를 담당할 정년 트랙 외 강사를 모집합니다.',
    quals: '- 한국어교육·한국학 박사 학위 (또는 임용 시점 박사 학위 예정자)\n- 대학에서 한국어 강의 경력 3년 이상\n- 영어 강의 가능자',
    preferred: '미국 대학 강의 경험, 교재 개발 경험',
    apply: 'UCLA Recruit 시스템에서 CV, Teaching Statement, Reference 3인 제출',
    badges: ['salary','visa','verified']
  },
  {
    id: 6, inst: 'toronto',
    title: 'Sessional Korean Language Instructor',
    country: '캐나다', region: 'Toronto, ON', type: '대학·대학원', employment: '시간강사', category: '강사', mode: '대면',
    salary: 'CAD 9,200 / course', salaryDisclosed: true,
    cert: '우대', degree: '석사', experience: '경력필수', visa: false,
    deadline: 14, posted: '4일 전', verified: true,
    desc: 'University of Toronto 동아시아학과에서 한국어 강의를 담당할 Sessional Instructor를 모집합니다.',
    quals: '- 한국어 교육 관련 석사 이상\n- 캐나다 영주권 또는 시민권 (또는 합법적 근로 비자 보유자)\n- 영어 강의 가능',
    preferred: '북미 대학 강의 경험자',
    apply: '학과 홈페이지에서 CV, Cover letter, Reference 제출',
    badges: ['salary','verified']
  },
  {
    id: 7, inst: 'waseda',
    title: '와세다대학 한국어 강의전임강사 (객원)',
    country: '일본', region: '도쿄', type: '대학·대학원', employment: '초빙·비전임', category: '강사', mode: '대면',
    salary: '협의 (연봉제)', salaryDisclosed: false,
    cert: '필수', degree: '석사', experience: '경력필수', visa: true,
    deadline: 45, posted: '6일 전', verified: true,
    desc: '와세다대학교 한국어 강의를 담당할 객원 강의전임강사를 모집합니다. 1년 계약 후 갱신 가능.',
    quals: '- 한국어교육 또는 한국학 석사 이상\n- 대학 강의 경력 2년 이상\n- 일본어 또는 영어로 강의 가능',
    preferred: '일본어 능력 N1 이상, 일본 대학 강의 경험자',
    apply: '학과 사무실 이메일 제출, 서류 통과 시 화상 면접',
    badges: ['visa','verified']
  },
  {
    id: 8, inst: 'sydney',
    title: 'Sessional Korean Tutor (Part-time, Semester 2)',
    country: '호주', region: 'Sydney, NSW', type: '대학·대학원', employment: '시간강사', category: '강사', mode: '대면',
    salary: 'AUD 75~95 / hour', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '신입가능', visa: false,
    deadline: 18, posted: '오늘', verified: true,
    desc: '시드니대학교 한국학 프로그램에서 학부생 한국어 튜토리얼을 담당할 시간강사를 모집합니다.',
    quals: '- 한국어 또는 한국학 관련 학사 이상\n- 호주 합법 근로 비자\n- 영어 가능',
    preferred: '한국어교원자격증 보유자, 한국어 교육 경력자',
    apply: 'Sydney Careers 포털에서 지원',
    badges: ['salary','junior','verified']
  },
  {
    id: 9, inst: 'hochiminh',
    title: '호치민 한국학과 정규 교수 채용 (정년트랙)',
    country: '베트남', region: '호치민', type: '대학·대학원', employment: '전임교원', category: '강사', mode: '대면',
    salary: '월 USD 1,800~2,500 + 주거 지원', salaryDisclosed: true,
    cert: '필수', degree: '박사', experience: '경력필수', visa: true,
    deadline: 60, posted: '7일 전', verified: false,
    desc: '베트남 호치민 인문사회과학대학 한국학과에서 한국어·한국학 강의를 담당할 정규 교수를 모집합니다.',
    quals: '- 한국학·한국어교육 박사 학위\n- 대학 강의 경력 5년 이상\n- 영어 강의 가능',
    preferred: '베트남어 가능자, 동남아 거주 경험자',
    apply: '학과 이메일로 CV·연구실적·자기소개서 제출',
    badges: ['salary','visa']
  },
  {
    id: 10, inst: 'gangnam',
    title: 'TOPIK 전문 한국어 강사 (강남)',
    country: '한국', region: '서울 강남구', type: '사설 어학원', employment: '시간강사', category: '강사', mode: '대면',
    salary: '시급 45,000~55,000원', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '신입가능', visa: false,
    deadline: 12, posted: '2일 전', verified: false,
    desc: '강남 토픽 한국어학원에서 TOPIK 시험 대비반 강사를 모집합니다. 평일 저녁 및 주말 수업.',
    quals: '- 한국어 또는 한국어교육 관련 전공 학사 이상\n- TOPIK 시험 또는 시험 대비 강의 경험',
    preferred: '한국어교원자격증 소지자, 영어·중국어 가능자',
    apply: '학원 홈페이지 채용 양식 제출',
    badges: ['salary','junior']
  },
  {
    id: 11, inst: 'italki',
    title: '온라인 1:1 한국어 튜터 모집 (전 세계 학습자 대상)',
    country: '온라인', region: '온라인', type: '온라인 플랫폼', employment: '프리랜서', category: '강사', mode: '온라인',
    salary: '시급 본인 설정 (USD 15~40 권장)', salaryDisclosed: false,
    cert: '우대', degree: '학사', experience: '신입가능', visa: false,
    deadline: 90, posted: '오늘', verified: false,
    desc: '전 세계 한국어 학습자와 1:1 화상 수업을 진행할 한국어 튜터를 상시 모집합니다. 본인이 일정·수업료를 자유롭게 설정.',
    quals: '- 한국어 원어민 또는 그에 준하는 능력\n- 영어 의사소통 가능\n- 안정적인 화상 수업 환경 (PC, 마이크, 인터넷)',
    preferred: '한국어교원자격증, 외국어 교습 경력',
    apply: '플랫폼 홈페이지에서 튜터 신청 → 영상 자기소개 업로드',
    badges: ['junior']
  },
  {
    id: 12, inst: 'preply',
    title: 'KoreanGo 정식 튜터 모집 (수업 매칭 지원)',
    country: '온라인', region: '온라인', type: '온라인 플랫폼', employment: '프리랜서', category: '강사', mode: '온라인',
    salary: '시급 USD 20~35 (수익 분배 모델)', salaryDisclosed: true,
    cert: '필수', degree: '학사', experience: '경력필수', visa: false,
    deadline: 6, posted: '4일 전', verified: false,
    desc: '한국어 학습 전문 플랫폼 KoreanGo의 정식 인증 튜터를 모집합니다. 플랫폼이 학습자 매칭과 결제를 관리합니다.',
    quals: '- 한국어교원자격증 보유자\n- 1:1 또는 그룹 한국어 수업 경력 1년 이상\n- 영어 소통 가능',
    preferred: 'TOPIK 대비, 비즈니스 한국어 가능자',
    apply: '플랫폼 가입 → 수업 시연 영상 제출 → 심사 통과',
    badges: ['salary','urgent']
  },
  {
    id: 13, inst: 'goyang',
    title: '고양초등학교 중도입국자녀·다문화학생 한국어교실 지도강사 채용',
    country: '한국', region: '경기 고양시', type: '초등학교', employment: '학교 강사', category: '강사', mode: '대면',
    salary: '시간당 32,000원', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '신입가능', visa: false,
    deadline: 6, posted: '오늘', verified: true,
    desc: '고양초등학교에서 중도입국자녀 및 다문화학생을 대상으로 한국어교실을 운영할 지도강사를 모집합니다. 학교 일과 시간 중 진행.',
    quals: '- 한국어 학습지도가 가능한 자\n- 한국어교원 자격증 소지자 또는 한국어교실 강사 경력자 우대\n- 퇴직교원 또는 관련 교원자격증 소지자',
    preferred: '맞춤형 한국어 학습지도 및 기초학력 지도 가능자',
    apply: '이메일 접수: pignet76@korea.kr (우편·방문도 가능)',
    badges: ['salary','urgent','junior']
  },
  {
    id: 14, inst: 'caritas',
    title: '인천 까리따스 이주민문화센터 사회통합프로그램 강사 모집',
    country: '한국', region: '인천', type: '다문화·가족센터', employment: '센터 강사', category: '강사', mode: '대면',
    salary: '협의 (사회통합프로그램 강사 보수 기준)', salaryDisclosed: false,
    cert: '필수', degree: '학사', experience: '경력필수', visa: false,
    deadline: 10, posted: '3일 전', verified: false,
    desc: '인천 까리따스 이주민문화센터에서 결혼이민자·이주민을 대상으로 사회통합프로그램 한국어 강의를 담당할 강사를 모집합니다.',
    quals: '- 한국어교원자격증 필수\n- 사회통합프로그램 강사 양성과정 이수자 우대\n- 외국인 대상 한국어 강의 경력 1년 이상',
    preferred: '다양한 국적 학습자 대상 강의 경험자, 영어·중국어 등 외국어 가능자',
    apply: '센터 이메일로 이력서·자기소개서 제출',
    badges: ['junior']
  }  ,
  {
    id: 15, inst: 'sejong',
    title: '세종학당재단 본부 한국어교육사업 운영원',
    country: '한국', region: '서울 종로', type: '세종학당', employment: '계약직', category: '행정·운영', mode: '대면',
    salary: '월 280~320만원', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '경력필수', visa: false,
    deadline: 14, posted: '3일 전', verified: true,
    desc: '세종학당재단 본부에서 해외 세종학당 교원 파견·운영 등 한국어교육 사업 행정을 담당할 직원을 모집합니다.',
    quals: '- 학사 이상\n- 한국어교육 또는 행정 관련 경력 2년 이상\n- 영어 가능자',
    preferred: '한국어교원자격증 보유자, 해외 거주 경험자',
    apply: '재단 채용 시스템 온라인 지원',
    badges: ['salary']
  },
  {
    id: 16, inst: 'darakwon',
    title: '다락원 한국어 교재 편집자 (정규직)',
    country: '한국', region: '서울 마포', type: '출판사', employment: '정규직', category: '교재·출판', mode: '대면',
    salary: '연봉 3,800~4,500만원', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '경력필수', visa: false,
    deadline: 21, posted: '5일 전', verified: true,
    desc: '외국인 학습자용 한국어 교재 편집·기획을 담당할 편집자를 모집합니다. 신간 교재 개발 + 기존 교재 개정.',
    quals: '- 한국어교육·국문학·교육공학 학사 이상\n- 출판 또는 교재 기획 경력 2년 이상',
    preferred: '한국어교원자격증, 출판사 근무 경험',
    apply: '이메일 지원: jobs@darakwon.co.kr',
    badges: ['salary']
  },
  {
    id: 17, inst: 'ebs',
    title: 'EBS 한국어 학습 콘텐츠 PD (계약직)',
    country: '한국', region: '경기 고양', type: '방송사', employment: '계약직', category: '콘텐츠 제작', mode: '대면',
    salary: '월 350~400만원', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '경력필수', visa: false,
    deadline: 10, posted: '2일 전', verified: true,
    desc: 'EBS 한국어 학습 콘텐츠 기획·제작을 담당할 PD. 방송, 유튜브, 학습 앱 콘텐츠 등.',
    quals: '- 학사 이상\n- 방송·영상 제작 경력 또는 한국어교육 경력 3년 이상',
    preferred: '한국어교육 콘텐츠 기획 경험, 영상 편집 가능자',
    apply: 'EBS 채용 페이지에서 지원',
    badges: ['salary','urgent']
  },
  {
    id: 18, inst: 'nikl',
    title: '국립국어원 한국어교육 전문연구원',
    country: '한국', region: '서울 강서', type: '연구기관', employment: '계약직', category: '연구·평가', mode: '대면',
    salary: '월 320~400만원', salaryDisclosed: true,
    cert: '필수', degree: '박사', experience: '경력필수', visa: false,
    deadline: 28, posted: '오늘', verified: true,
    desc: '국립국어원에서 한국어교육 정책 연구, TOPIK 시험 개발, 교재 평가 등을 담당할 전문연구원을 모집합니다.',
    quals: '- 한국어교육·국어학 박사 학위\n- 한국어교육 관련 연구·논문 실적\n- 한국어교원자격증 보유',
    preferred: 'TOPIK 출제 경험, 영어 가능자',
    apply: '국립국어원 채용 공고 페이지',
    badges: ['salary']
  },
  {
    id: 19, inst: 'kccuk',
    title: '주영국 한국문화원 한국어 교육 코디네이터',
    country: '영국', region: 'London', type: '공공기관', employment: '계약직', category: '정책·국제교류', mode: '대면',
    salary: 'GBP 28,000~32,000 / year', salaryDisclosed: true,
    cert: '우대', degree: '학사', experience: '경력필수', visa: true,
    deadline: 35, posted: '4일 전', verified: true,
    desc: '주영국 한국문화원에서 한국어 강좌 운영, 강사 관리, 한국어교육 프로그램 기획을 담당할 코디네이터.',
    quals: '- 학사 이상\n- 한국어교육 또는 국제교류 경력 2년 이상\n- 영어 능통',
    preferred: '한국어교원자격증, 해외 거주·근무 경험',
    apply: '문화원 이메일 지원',
    badges: ['salary','visa']
  },
  {
    id: 20, inst: 'kef',
    title: '한국어교육진흥재단 정책 연구원 (정규직)',
    country: '한국', region: '서울', type: '연구기관', employment: '정규직', category: '연구·평가', mode: '대면',
    salary: '연봉 4,500~5,500만원', salaryDisclosed: true,
    cert: '우대', degree: '석사', experience: '경력필수', visa: false,
    deadline: 45, posted: '6일 전', verified: true,
    desc: '한국어교육 진흥 재단에서 정책 연구, 사업 기획, 보고서 작성 등을 담당할 정규직 연구원을 모집합니다.',
    quals: '- 한국어교육·교육정책 석사 이상\n- 정책 연구·보고서 작성 경력 3년 이상',
    preferred: '한국어교육 관련 학회 활동 경험, 영어 가능자',
    apply: '재단 홈페이지에서 지원',
    badges: ['salary']
  }
];
